//
//  AISuggestionService.swift
//  Little Artist
//
//  Provides AI-powered title and caption suggestions for artwork.
//  Uses Firebase Vertex AI (Gemini) as the primary analysis engine
//  with on-device Apple FoundationModels as a fallback.
//

import FirebaseVertexAI
import Foundation
import UIKit
import Vision
import CoreImage
#if canImport(FoundationModels)
import FoundationModels
#endif

// MARK: - AI Suggestion Result

/// A title and caption pair generated by AI analysis.
struct AISuggestion: Decodable {
    let title: String
    let caption: String
}

// MARK: - AI Suggestion Service

/// Centralised service for generating AI-powered artwork suggestions.
///
/// Attempts cloud-based analysis via Firebase Vertex AI (Gemini) first,
/// which can directly see the artwork image for higher quality results.
/// Falls back to on-device Vision + FoundationModels when the cloud
/// service is unavailable (offline, quota exceeded, etc.).
enum AISuggestionService {

    // MARK: - Availability

    /// Whether AI suggestions are available (cloud or on-device).
    /// Cloud is always nominally available; on-device requires iOS 26+.
    static var isAvailable: Bool {
        true
    }

    /// Whether on-device AI is available as a fallback.
    private static var isOnDeviceAvailable: Bool {
        #if canImport(FoundationModels)
        if #available(iOS 26.0, *) {
            return SystemLanguageModel.default.isAvailable
        }
        #endif
        return false
    }

    // MARK: - Gemini (Cloud) Model

    /// Lazy-initialised Gemini model via Firebase Vertex AI.
    private static let geminiModel: GenerativeModel = {
        VertexAI.vertexAI().generativeModel(modelName: "gemini-2.0-flash")
    }()

    // MARK: - System Prompts

    private static let generateSystemInstruction = """
        You name children's artwork with creative, fun, short titles.
        You are given an image of the artwork. Focus on the SUBJECTS and SCENES
        depicted (animals, people, flowers, houses, landscapes, etc.), not the colours or medium.
        Rules:
        - Title: 2-4 words, creative and playful, like a storybook name. Never include the child's name. Never list colours. Never say "drawing" or "painting".
        - Caption: One warm sentence (max 15 words) celebrating what the child created. Be specific about subjects.
        Return ONLY valid JSON: {"title":"...","caption":"..."}
        """

    private static let improveSystemInstruction = """
        You improve titles and captions for children's artwork.
        You are given an image of the artwork. Focus on the SUBJECTS and SCENES depicted, not colours or medium.
        Rules:
        - Title: 2-4 words, creative and playful. Never include the child's name. Never list colours. Never say "drawing" or "painting".
        - Caption: One warm sentence (max 15 words) celebrating what the child created.
        Return ONLY valid JSON: {"title":"...","caption":"..."}
        """

    // MARK: - Suggestion Generation

    /// Generates a new title and caption for a child's artwork.
    ///
    /// Tries Gemini (cloud) first for multimodal image analysis,
    /// then falls back to on-device Vision + FoundationModels.
    static func generateSuggestions(imageData: Data, childName: String) async throws -> AISuggestion {
        // Try cloud-based Gemini first
        do {
            return try await generateWithGemini(imageData: imageData, childName: childName)
        } catch {
            // Fall back to on-device
            return try await generateOnDevice(imageData: imageData, childName: childName)
        }
    }

    /// Improves an existing title and caption for a child's artwork.
    ///
    /// Tries Gemini (cloud) first, then falls back to on-device.
    static func improveSuggestions(
        imageData: Data?,
        existingTitle: String,
        existingCaption: String,
        childName: String
    ) async throws -> AISuggestion {
        // Try cloud-based Gemini first
        do {
            return try await improveWithGemini(
                imageData: imageData,
                existingTitle: existingTitle,
                existingCaption: existingCaption,
                childName: childName
            )
        } catch {
            // Fall back to on-device
            return try await improveOnDevice(
                imageData: imageData,
                existingTitle: existingTitle,
                existingCaption: existingCaption,
                childName: childName
            )
        }
    }

    // MARK: - Gemini (Cloud) Implementation

    /// Generates suggestions using Gemini multimodal analysis.
    private static func generateWithGemini(imageData: Data, childName: String) async throws -> AISuggestion {
        guard let image = UIImage(data: imageData) else {
            throw AISuggestionError.invalidImage
        }

        let prompt = """
        \(generateSystemInstruction)

        Child: \(childName)
        Name this artwork with a fun, imaginative title and a warm caption about what \(childName) drew.
        """

        let response = try await geminiModel.generateContent(image, prompt)

        guard let text = response.text else {
            throw AISuggestionError.emptyResponse
        }

        return parseSuggestions(from: text)
    }

    /// Improves suggestions using Gemini multimodal analysis.
    private static func improveWithGemini(
        imageData: Data?,
        existingTitle: String,
        existingCaption: String,
        childName: String
    ) async throws -> AISuggestion {
        let prompt = """
        \(improveSystemInstruction)

        Child: \(childName)
        Current title: \(existingTitle.isEmpty ? "None" : existingTitle)
        Current caption: \(existingCaption.isEmpty ? "None" : existingCaption)
        Improve the title and caption to be more creative and specific to the artwork.
        """

        let response: GenerateContentResponse
        if let imageData, let image = UIImage(data: imageData) {
            response = try await geminiModel.generateContent(image, prompt)
        } else {
            response = try await geminiModel.generateContent(prompt)
        }

        guard let text = response.text else {
            throw AISuggestionError.emptyResponse
        }

        return parseSuggestions(from: text)
    }

    // MARK: - On-Device Fallback Implementation

    /// Generates suggestions using on-device Vision analysis + FoundationModels.
    private static func generateOnDevice(imageData: Data, childName: String) async throws -> AISuggestion {
        #if canImport(FoundationModels)
        if #available(iOS 26.0, *), isOnDeviceAvailable {
            let imageAnalysis = analyseImage(imageData)

            let session = LanguageModelSession(
                instructions: generateSystemInstruction
            )

            let prompt = """
            Child: \(childName)
            What the artwork shows: \(imageAnalysis)
            Name this artwork with a fun, imaginative title and a warm caption about what \(childName) drew.
            """

            do {
                let response = try await session.respond(to: prompt)
                return parseSuggestions(from: response.content)
            } catch {
                try await Task.sleep(for: .milliseconds(350))
                let retryResponse = try await session.respond(to: prompt)
                return parseSuggestions(from: retryResponse.content)
            }
        }
        #endif
        return AISuggestion(title: "My Artwork", caption: "A colorful creation full of imagination.")
    }

    /// Improves suggestions using on-device Vision analysis + FoundationModels.
    private static func improveOnDevice(
        imageData: Data?,
        existingTitle: String,
        existingCaption: String,
        childName: String
    ) async throws -> AISuggestion {
        #if canImport(FoundationModels)
        if #available(iOS 26.0, *), isOnDeviceAvailable {
            let imageAnalysis = imageData.map { analyseImage($0) } ?? "No image available"

            let session = LanguageModelSession(
                instructions: improveSystemInstruction
            )

            let prompt = """
            Child: \(childName)
            Current title: \(existingTitle.isEmpty ? "None" : existingTitle)
            Current caption: \(existingCaption.isEmpty ? "None" : existingCaption)
            What the artwork shows: \(imageAnalysis)
            Improve the title and caption to be more creative and specific to the artwork.
            """

            do {
                let response = try await session.respond(to: prompt)
                return parseSuggestions(from: response.content)
            } catch {
                try await Task.sleep(for: .milliseconds(350))
                let retryResponse = try await session.respond(to: prompt)
                return parseSuggestions(from: retryResponse.content)
            }
        }
        #endif
        return AISuggestion(title: "My Artwork", caption: "A colorful creation full of imagination.")
    }

    // MARK: - Image Analysis (On-Device Fallback)

    /// Analyses an artwork image using Vision classification and OCR.
    ///
    /// Used only for the on-device fallback path where the language model
    /// cannot see the image directly.
    static func analyseImage(_ imageData: Data) -> String {
        guard let image = UIImage(data: imageData), let cgImage = image.cgImage else {
            return "Unable to process image"
        }

        var descriptions: [String] = []

        // 1. Image classification — identifies objects, scenes, and themes
        let classifyRequest = VNClassifyImageRequest()
        let handler = VNImageRequestHandler(cgImage: cgImage)
        do {
            try handler.perform([classifyRequest])
            let topLabels = (classifyRequest.results ?? [])
                .filter { $0.confidence > 0.3 }
                .sorted { $0.confidence > $1.confidence }
                .prefix(10)
                .map { "\($0.identifier) (\(Int($0.confidence * 100))%)" }
            if !topLabels.isEmpty {
                descriptions.append("Visual content: \(topLabels.joined(separator: ", "))")
            }
        } catch {
            // Classification failed, continue with other analysis
        }

        // 2. OCR — extract any text written in the artwork
        let textRequest = VNRecognizeTextRequest()
        textRequest.recognitionLevel = .accurate
        textRequest.usesLanguageCorrection = true
        let textHandler = VNImageRequestHandler(cgImage: cgImage)
        do {
            try textHandler.perform([textRequest])
            let lines = (textRequest.results ?? [])
                .compactMap { $0.topCandidates(1).first?.string }
                .prefix(6)
            if !lines.isEmpty {
                descriptions.append("Text in image: \(lines.joined(separator: ", "))")
            }
        } catch {
            // OCR failed, continue
        }

        // 3. Dominant colours — describe the colour palette
        let colours = extractDominantColours(from: cgImage)
        if !colours.isEmpty {
            descriptions.append("Dominant colours: \(colours.joined(separator: ", "))")
        }

        // 4. Basic image properties
        let width = cgImage.width
        let height = cgImage.height
        let orientation = width > height ? "landscape" : (height > width ? "portrait" : "square")
        descriptions.append("Format: \(orientation)")

        return descriptions.isEmpty ? "No visual details detected" : descriptions.joined(separator: ". ")
    }

    /// Extracts dominant colour names from an image using CIAreaHistogram.
    private static func extractDominantColours(from cgImage: CGImage) -> [String] {
        let ciImage = CIImage(cgImage: cgImage)
        let context = CIContext()

        // Sample colours from a grid of points across the image
        let width = CGFloat(cgImage.width)
        let height = CGFloat(cgImage.height)
        var colourCounts: [String: Int] = [:]

        let samplePoints = 5
        for row in 0..<samplePoints {
            for col in 0..<samplePoints {
                let x = width * CGFloat(col) / CGFloat(samplePoints) + width / CGFloat(samplePoints * 2)
                let y = height * CGFloat(row) / CGFloat(samplePoints) + height / CGFloat(samplePoints * 2)
                let rect = CGRect(x: x, y: y, width: 1, height: 1)

                guard let filter = CIFilter(name: "CIAreaAverage", parameters: [
                    kCIInputImageKey: ciImage,
                    kCIInputExtentKey: CIVector(cgRect: rect)
                ]),
                let outputImage = filter.outputImage else { continue }

                var pixel = [UInt8](repeating: 0, count: 4)
                context.render(outputImage, toBitmap: &pixel, rowBytes: 4,
                              bounds: CGRect(x: 0, y: 0, width: 1, height: 1),
                              format: .RGBA8, colorSpace: CGColorSpaceCreateDeviceRGB())

                let name = colourName(r: pixel[0], g: pixel[1], b: pixel[2])
                colourCounts[name, default: 0] += 1
            }
        }

        return colourCounts
            .sorted { $0.value > $1.value }
            .prefix(4)
            .map { $0.key }
    }

    /// Maps RGB values to a human-readable colour name.
    private static func colourName(r: UInt8, g: UInt8, b: UInt8) -> String {
        let rf = Double(r) / 255.0
        let gf = Double(g) / 255.0
        let bf = Double(b) / 255.0

        let maxC = max(rf, gf, bf)
        let minC = min(rf, gf, bf)
        let brightness = (maxC + minC) / 2.0
        let saturation = maxC == minC ? 0 : (maxC - minC) / (1.0 - abs(2 * brightness - 1))

        if brightness < 0.15 { return "black" }
        if brightness > 0.9 && saturation < 0.1 { return "white" }
        if saturation < 0.12 { return brightness > 0.5 ? "light gray" : "dark gray" }

        // Calculate hue
        var hue: Double = 0
        if maxC == rf {
            hue = 60.0 * (((gf - bf) / (maxC - minC)).truncatingRemainder(dividingBy: 6))
        } else if maxC == gf {
            hue = 60.0 * (((bf - rf) / (maxC - minC)) + 2)
        } else {
            hue = 60.0 * (((rf - gf) / (maxC - minC)) + 4)
        }
        if hue < 0 { hue += 360 }

        switch hue {
        case 0..<15: return "red"
        case 15..<40: return "orange"
        case 40..<70: return "yellow"
        case 70..<160: return "green"
        case 160..<200: return "teal"
        case 200..<250: return "blue"
        case 250..<290: return "purple"
        case 290..<330: return "pink"
        default: return "red"
        }
    }

    // MARK: - OCR (legacy helper)

    /// Extracts readable text from artwork image data using Vision OCR.
    static func extractText(from imageData: Data) -> String {
        guard let image = UIImage(data: imageData), let cgImage = image.cgImage else {
            return ""
        }

        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.usesLanguageCorrection = true

        let handler = VNImageRequestHandler(cgImage: cgImage)
        do {
            try handler.perform([request])
        } catch {
            return ""
        }

        let lines = (request.results ?? [])
            .compactMap { $0.topCandidates(1).first?.string }
            .prefix(6)

        return lines.joined(separator: ", ")
    }

    // MARK: - Parsing

    /// Parses an `AISuggestion` from raw language model output.
    static func parseSuggestions(from content: String) -> AISuggestion {
        // Try JSON extraction first
        if let jsonRange = content.range(of: #"\{[\s\S]*\}"#, options: .regularExpression) {
            let jsonString = String(content[jsonRange])
            if let data = jsonString.data(using: .utf8),
               let decoded = try? JSONDecoder().decode(AISuggestion.self, from: data) {
                let cleanTitle = sanitize(decoded.title)
                let cleanCaption = sanitize(decoded.caption)
                if !cleanTitle.isEmpty || !cleanCaption.isEmpty {
                    return AISuggestion(
                        title: cleanTitle.isEmpty ? "My Artwork" : cleanTitle,
                        caption: cleanCaption.isEmpty ? "A colorful creation full of imagination." : cleanCaption
                    )
                }
            }
        }

        // Fallback: line-by-line parsing
        var parsedTitle = ""
        var parsedCaption = ""
        for line in content.split(separator: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.lowercased().hasPrefix("title:") {
                parsedTitle = String(trimmed.dropFirst("title:".count))
            } else if trimmed.lowercased().hasPrefix("caption:") {
                parsedCaption = String(trimmed.dropFirst("caption:".count))
            }
        }

        let cleanTitle = sanitize(parsedTitle)
        let cleanCaption = sanitize(parsedCaption)

        return AISuggestion(
            title: cleanTitle.isEmpty ? "My Artwork" : cleanTitle,
            caption: cleanCaption.isEmpty ? "A colorful creation full of imagination." : cleanCaption
        )
    }

    /// Strips leading/trailing whitespace, newlines, and surrounding quotes.
    private static func sanitize(_ text: String) -> String {
        text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
    }
}

// MARK: - Errors

/// Errors specific to AI suggestion generation.
enum AISuggestionError: Error {
    case invalidImage
    case emptyResponse
}
