//
//  AISuggestionService.swift
//  Little Artist
//
//  Provides AI-powered title and caption suggestions for artwork.
//  Uses Firebase Vertex AI (Gemini) as the primary analysis engine
//  with on-device Apple FoundationModels as a fallback.
//

import FirebaseAI
import Foundation
import UIKit
import Vision

// MARK: - AI Suggestion Result

/// A title and caption pair generated by AI analysis.
struct AISuggestion: Decodable {
    let title: String
    let caption: String
}

// MARK: - Artwork Validation Result

/// Result of validating whether an image is children's artwork.
struct ArtworkValidationResult {
    /// Whether the image appears to be children's artwork or a creative piece.
    let isArtwork: Bool
    /// Whether the image content is appropriate for a children's app.
    let isAppropriate: Bool
    /// A user-facing message explaining why the image was flagged.
    let message: String?

    /// Image passed all checks.
    static let valid = ArtworkValidationResult(isArtwork: true, isAppropriate: true, message: nil)
}

// MARK: - AI Suggestion Service

/// Centralised service for generating AI-powered artwork suggestions.
///
/// Uses cloud-based analysis via Firebase Vertex AI (Gemini),
/// which can directly see the artwork image for higher quality results.
/// If the cloud request fails, returns safe default text.
/// All Gemini calls are gated by `GeminiUsageTracker` rate limits.
enum AISuggestionService {

    // MARK: - Availability

    /// Whether AI suggestions are available.
    /// Actual usage limits are enforced at the point of each Gemini API call.
    static var isAvailable: Bool {
        true
    }

    // MARK: - Gemini (Cloud) Model

    /// Preferred Gemini model names in order of priority.
    private static let geminiModelNames = [
        "gemini-2.5-flash",
        "gemini-2.5-flash-lite",
        "gemini-2.0-flash-001"
    ]

    // MARK: - System Prompts

    private static let generateSystemInstruction = """
        You name children's artwork with creative, fun, short titles.
        You are given an image of the artwork. Focus on the SUBJECTS and SCENES
        depicted (animals, people, flowers, houses, landscapes, etc.), not the colours or medium.
        Rules:
        - Title: 2-4 words, creative and playful, like a storybook name. Never include the child's name. Never list colours. Never say "drawing" or "painting".
        - Caption: One warm sentence (max 15 words) celebrating what the child created. Be specific about subjects.
        Return ONLY valid JSON: {"title":"...","caption":"..."}
        """

    private static let improveSystemInstruction = """
        You improve titles and captions for children's artwork.
        You are given an image of the artwork. Focus on the SUBJECTS and SCENES depicted, not colours or medium.
        Rules:
        - Title: 2-4 words, creative and playful. Never include the child's name. Never list colours. Never say "drawing" or "painting".
        - Caption: One warm sentence (max 15 words) celebrating what the child created.
        Return ONLY valid JSON: {"title":"...","caption":"..."}
        """

    // MARK: - Image Validation

    /// Validates whether an image is children's artwork.
    ///
    /// Tries Gemini (cloud) first for accurate multimodal classification,
    /// then falls back to on-device Vision classification heuristics.
    /// Returns a result indicating whether the image is artwork and appropriate.
    static func validateArtwork(imageData: Data) async -> ArtworkValidationResult {
        // Try cloud-based Gemini first
        do {
            return try await validateWithGemini(imageData: imageData)
        } catch {
            // Fall back to on-device Vision classification
            return validateOnDevice(imageData: imageData)
        }
    }

    /// Validates an image using Gemini multimodal analysis.
    private static func validateWithGemini(imageData: Data) async throws -> ArtworkValidationResult {
        guard let image = UIImage(data: imageData) else {
            throw AISuggestionError.invalidImage
        }

        let prompt = """
        You are a content classifier for a children's artwork archiving app.
        Analyse this image and classify it. Return ONLY valid JSON with these fields:
        - "is_artwork": true if this is children's artwork, a drawing, painting, craft, \
        collage, sketch, colouring page, or any creative piece made by a child. \
        Photos OF artwork (e.g. a painting hanging on a wall or lying on a table) also count as true. \
        false if this is a regular photograph, screenshot, meme, or unrelated image.
        - "is_appropriate": true if the content is appropriate for a family/children's app. \
        false if it contains nudity, violence, gore, drugs, weapons, or other adult content.
        - "reason": a short (max 12 words) description of what the image shows \
        (e.g. "A photograph of a child", "A crayon drawing of a house", "An inappropriate image").

        Return ONLY: {"is_artwork":bool,"is_appropriate":bool,"reason":"..."}
        """

        let response = try await generateGeminiContent(image: image, prompt: prompt)

        guard let text = response.text else {
            throw AISuggestionError.emptyResponse
        }

        return parseValidationResult(from: text)
    }

    /// Validates an image using on-device Vision classification heuristics.
    private static func validateOnDevice(imageData: Data) -> ArtworkValidationResult {
        guard let image = UIImage(data: imageData), let cgImage = image.cgImage else {
            return .valid // Can't analyse — allow through
        }

        // Run Vision classification
        let classifyRequest = VNClassifyImageRequest()
        let handler = VNImageRequestHandler(cgImage: cgImage)
        do {
            try handler.perform([classifyRequest])
        } catch {
            return .valid // Classification failed — allow through
        }

        let results = classifyRequest.results ?? []
        let labelMap = Dictionary(uniqueKeysWithValues: results.map { ($0.identifier, $0.confidence) })

        // Check for photos of people (not artwork)
        let personScore = labelMap["person"] ?? 0
        let faceScore = labelMap["face"] ?? 0
        let portraitScore = labelMap["portrait"] ?? 0
        let selfieScore = labelMap["selfie"] ?? 0
        let peopleTotalScore = max(personScore, faceScore, portraitScore, selfieScore)

        // Check for artwork-like signals
        let drawingScore = labelMap["drawing"] ?? 0
        let paintingScore = labelMap["painting"] ?? 0
        let artScore = labelMap["art"] ?? 0
        let sketchScore = labelMap["sketch"] ?? 0
        let crayonScore = labelMap["crayon"] ?? 0
        let artworkTotalScore = max(drawingScore, paintingScore, artScore, sketchScore, crayonScore)

        // If strong person signal and weak artwork signal, it's probably a photo of someone
        if peopleTotalScore > 0.6 && artworkTotalScore < 0.3 {
            return ArtworkValidationResult(
                isArtwork: false,
                isAppropriate: true,
                message: "This looks like a photo of a person rather than artwork."
            )
        }

        // Check for screenshots / UI
        let screenshotScore = labelMap["screenshot"] ?? 0
        let webScore = labelMap["web_page"] ?? 0
        if max(screenshotScore, webScore) > 0.6 && artworkTotalScore < 0.2 {
            return ArtworkValidationResult(
                isArtwork: false,
                isAppropriate: true,
                message: "This looks like a screenshot rather than artwork."
            )
        }

        // Check for nature/landscape photos (not artwork)
        let landscapeScore = labelMap["landscape"] ?? 0
        let outdoorScore = labelMap["outdoor"] ?? 0
        let buildingScore = labelMap["building"] ?? 0
        let photoScore = max(landscapeScore, outdoorScore, buildingScore)
        if photoScore > 0.7 && artworkTotalScore < 0.2 {
            return ArtworkValidationResult(
                isArtwork: false,
                isAppropriate: true,
                message: "This looks like a photograph rather than artwork."
            )
        }

        return .valid
    }

    /// Parses a validation result from Gemini's JSON response.
    private static func parseValidationResult(from content: String) -> ArtworkValidationResult {
        guard let jsonRange = content.range(of: #"\{[\s\S]*\}"#, options: .regularExpression) else {
            return .valid // Can't parse — allow through
        }

        let jsonString = String(content[jsonRange])
        guard let data = jsonString.data(using: .utf8) else {
            return .valid
        }

        struct ValidationResponse: Decodable {
            let is_artwork: Bool
            let is_appropriate: Bool
            let reason: String
        }

        guard let decoded = try? JSONDecoder().decode(ValidationResponse.self, from: data) else {
            return .valid
        }

        if decoded.is_artwork && decoded.is_appropriate {
            return .valid
        }

        var message: String
        if !decoded.is_appropriate {
            message = "This image doesn't appear appropriate for a children's app."
        } else {
            message = "This doesn't look like artwork. \(decoded.reason.prefix(60))"
        }

        return ArtworkValidationResult(
            isArtwork: decoded.is_artwork,
            isAppropriate: decoded.is_appropriate,
            message: message
        )
    }

    // MARK: - Suggestion Generation

    /// Generates a new title and caption for a child's artwork.
    ///
    /// Uses Gemini multimodal image analysis.
    static func generateSuggestions(imageData: Data, childName: String) async throws -> AISuggestion {
        do {
            return try await generateWithGemini(imageData: imageData, childName: childName)
        } catch {
            return AISuggestion(
                title: "My Artwork",
                caption: "A colorful creation full of imagination."
            )
        }
    }

    /// Improves an existing title and caption for a child's artwork.
    ///
    /// Uses Gemini multimodal image analysis.
    static func improveSuggestions(
        imageData: Data?,
        existingTitle: String,
        existingCaption: String,
        childName: String
    ) async throws -> AISuggestion {
        do {
            return try await improveWithGemini(
                imageData: imageData,
                existingTitle: existingTitle,
                existingCaption: existingCaption,
                childName: childName
            )
        } catch {
            return AISuggestion(
                title: existingTitle.isEmpty ? "My Artwork" : existingTitle,
                caption: existingCaption.isEmpty ? "A colorful creation full of imagination." : existingCaption
            )
        }
    }

    // MARK: - Gemini (Cloud) Implementation

    /// Generates suggestions using Gemini multimodal analysis.
    private static func generateWithGemini(imageData: Data, childName: String) async throws -> AISuggestion {
        guard let image = UIImage(data: imageData) else {
            throw AISuggestionError.invalidImage
        }

        let prompt = """
        \(generateSystemInstruction)

        Child: \(childName)
        Name this artwork with a fun, imaginative title and a warm caption about what \(childName) drew.
        """

        let response = try await generateGeminiContent(image: image, prompt: prompt)

        guard let text = response.text else {
            throw AISuggestionError.emptyResponse
        }

        return parseSuggestions(from: text)
    }

    /// Improves suggestions using Gemini multimodal analysis.
    private static func improveWithGemini(
        imageData: Data?,
        existingTitle: String,
        existingCaption: String,
        childName: String
    ) async throws -> AISuggestion {
        let prompt = """
        \(improveSystemInstruction)

        Child: \(childName)
        Current title: \(existingTitle.isEmpty ? "None" : existingTitle)
        Current caption: \(existingCaption.isEmpty ? "None" : existingCaption)
        Improve the title and caption to be more creative and specific to the artwork.
        """

        let response: GenerateContentResponse
        if let imageData, let image = UIImage(data: imageData) {
            response = try await generateGeminiContent(image: image, prompt: prompt)
        } else {
            response = try await generateGeminiContent(prompt: prompt)
        }

        guard let text = response.text else {
            throw AISuggestionError.emptyResponse
        }

        return parseSuggestions(from: text)
    }

    /// Generates content using the first available Gemini model in priority order.
    /// Checks usage limits before making the request and records usage on success.
    private static func generateGeminiContent(prompt: String) async throws -> GenerateContentResponse {
        try await MainActor.run { try checkUsageLimit() }

        var lastError: Error?
        for modelName in geminiModelNames {
            do {
                let model = FirebaseAI.firebaseAI(backend: .googleAI()).generativeModel(modelName: modelName)
                let response = try await model.generateContent(prompt)
                await MainActor.run { GeminiUsageTracker.shared.recordRequest() }
                return response
            } catch {
                lastError = error
            }
        }
        throw lastError ?? AISuggestionError.emptyResponse
    }

    /// Generates multimodal content using the first available Gemini model in priority order.
    /// Checks usage limits before making the request and records usage on success.
    private static func generateGeminiContent(image: UIImage, prompt: String) async throws -> GenerateContentResponse {
        try await MainActor.run { try checkUsageLimit() }

        var lastError: Error?
        for modelName in geminiModelNames {
            do {
                let model = FirebaseAI.firebaseAI(backend: .googleAI()).generativeModel(modelName: modelName)
                let response = try await model.generateContent(image, prompt)
                await MainActor.run { GeminiUsageTracker.shared.recordRequest() }
                return response
            } catch {
                lastError = error
            }
        }
        throw lastError ?? AISuggestionError.emptyResponse
    }

    /// Checks the usage tracker and throws if the rate limit is exceeded.
    @MainActor
    private static func checkUsageLimit() throws {
        let tracker = GeminiUsageTracker.shared
        guard tracker.canMakeRequest else {
            let message = tracker.exceededLimit?.message
                ?? "AI usage limit reached. Please try again later."
            throw AISuggestionError.rateLimitExceeded(message: message)
        }
    }

    // MARK: - Parsing

    /// Parses an `AISuggestion` from raw language model output.
    static func parseSuggestions(from content: String) -> AISuggestion {
        // Try JSON extraction first
        if let jsonRange = content.range(of: #"\{[\s\S]*\}"#, options: .regularExpression) {
            let jsonString = String(content[jsonRange])
            if let data = jsonString.data(using: .utf8),
               let decoded = try? JSONDecoder().decode(AISuggestion.self, from: data) {
                let cleanTitle = sanitize(decoded.title)
                let cleanCaption = sanitize(decoded.caption)
                if !cleanTitle.isEmpty || !cleanCaption.isEmpty {
                    return AISuggestion(
                        title: cleanTitle.isEmpty ? "My Artwork" : cleanTitle,
                        caption: cleanCaption.isEmpty ? "A colorful creation full of imagination." : cleanCaption
                    )
                }
            }
        }

        // Fallback: line-by-line parsing
        var parsedTitle = ""
        var parsedCaption = ""
        for line in content.split(separator: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.lowercased().hasPrefix("title:") {
                parsedTitle = String(trimmed.dropFirst("title:".count))
            } else if trimmed.lowercased().hasPrefix("caption:") {
                parsedCaption = String(trimmed.dropFirst("caption:".count))
            }
        }

        let cleanTitle = sanitize(parsedTitle)
        let cleanCaption = sanitize(parsedCaption)

        return AISuggestion(
            title: cleanTitle.isEmpty ? "My Artwork" : cleanTitle,
            caption: cleanCaption.isEmpty ? "A colorful creation full of imagination." : cleanCaption
        )
    }

    /// Strips leading/trailing whitespace, newlines, and surrounding quotes.
    private static func sanitize(_ text: String) -> String {
        text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
    }
}

// MARK: - Errors

/// Errors specific to AI suggestion generation.
enum AISuggestionError: LocalizedError {
    case invalidImage
    case emptyResponse
    case rateLimitExceeded(message: String)

    var errorDescription: String? {
        switch self {
        case .invalidImage:
            return "The image could not be processed."
        case .emptyResponse:
            return "No response was received from the AI service."
        case .rateLimitExceeded(let message):
            return message
        }
    }
}
