//
//  AISuggestionService.swift
//  Little Artist
//
//  Provides on-device AI-powered title and caption suggestions for artwork
//  using Apple's FoundationModels framework and Vision OCR.
//

import Foundation
import UIKit
import Vision
#if canImport(FoundationModels)
import FoundationModels
#endif

// MARK: - AI Suggestion Result

/// A title and caption pair generated by the on-device language model.
struct AISuggestion: Decodable {
    let title: String
    let caption: String
}

// MARK: - AI Suggestion Service

/// Centralised service for generating AI-powered artwork suggestions.
///
/// Uses Vision OCR to extract text from artwork images, then feeds the
/// extracted text into Apple's on-device `FoundationModels` framework
/// to produce short, child-friendly titles and captions.
enum AISuggestionService {

    /// Whether on-device AI suggestions are available on this device.
    static var isAvailable: Bool {
        #if canImport(FoundationModels)
        if #available(iOS 26.0, *) {
            return SystemLanguageModel.default.isAvailable
        }
        #endif
        return false
    }

    // MARK: - OCR

    /// Extracts readable text from artwork image data using Vision OCR.
    ///
    /// - Parameter imageData: The raw image bytes to analyse.
    /// - Returns: A comma-separated string of recognised text lines (up to 6).
    static func extractText(from imageData: Data) -> String {
        guard let image = UIImage(data: imageData), let cgImage = image.cgImage else {
            return ""
        }

        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.usesLanguageCorrection = true

        let handler = VNImageRequestHandler(cgImage: cgImage)
        do {
            try handler.perform([request])
        } catch {
            return ""
        }

        let lines = (request.results ?? [])
            .compactMap { $0.topCandidates(1).first?.string }
            .prefix(6)

        return lines.joined(separator: ", ")
    }

    // MARK: - Suggestion Generation

    /// Generates a new title and caption for a child's artwork.
    ///
    /// - Parameters:
    ///   - imageData: The artwork image data for OCR analysis.
    ///   - childName: The name of the child artist.
    /// - Returns: An `AISuggestion` containing a title and caption.
    /// - Throws: If the language model session fails after retry.
    @available(iOS 26.0, *)
    static func generateSuggestions(imageData: Data, childName: String) async throws -> AISuggestion {
        #if canImport(FoundationModels)
        let extractedText = extractText(from: imageData)

        let session = LanguageModelSession(
            instructions: """
            You create short, joyful title and caption suggestions for a child's artwork.
            Keep language family-friendly and specific.
            Return ONLY valid JSON in this exact shape:
            {"title":"...","caption":"..."}
            Do not return markdown or extra keys.
            """
        )

        let prompt = """
        Child name: \(childName)
        OCR text found in image: \(extractedText.isEmpty ? "None" : extractedText)
        Generate one unique title (max 5 words) and one unique caption (1 sentence, max 18 words).
        """

        do {
            let response = try await session.respond(to: prompt)
            return parseSuggestions(from: response.content)
        } catch {
            // Retry once — the first call can fail while the model warms up.
            try await Task.sleep(for: .milliseconds(350))
            let retryResponse = try await session.respond(to: prompt)
            return parseSuggestions(from: retryResponse.content)
        }
        #else
        return AISuggestion(title: "My Artwork", caption: "A colorful creation full of imagination.")
        #endif
    }

    /// Improves an existing title and caption for a child's artwork.
    ///
    /// - Parameters:
    ///   - imageData: The artwork image data for OCR analysis.
    ///   - existingTitle: The current title to improve.
    ///   - existingCaption: The current caption to improve.
    ///   - childName: The name of the child artist.
    /// - Returns: An `AISuggestion` with the improved title and caption.
    /// - Throws: If the language model session fails after retry.
    @available(iOS 26.0, *)
    static func improveSuggestions(
        imageData: Data?,
        existingTitle: String,
        existingCaption: String,
        childName: String
    ) async throws -> AISuggestion {
        #if canImport(FoundationModels)
        let extractedText = imageData.map { extractText(from: $0) } ?? ""

        let session = LanguageModelSession(
            instructions: """
            You improve title and caption text for a child's artwork.
            Keep language warm, family-friendly, and concise.
            Return ONLY valid JSON in this exact shape:
            {"title":"...","caption":"..."}
            Do not return markdown or extra keys.
            """
        )

        let prompt = """
        Child name: \(childName)
        Existing title: \(existingTitle.isEmpty ? "None" : existingTitle)
        Existing caption: \(existingCaption.isEmpty ? "None" : existingCaption)
        OCR text found in image: \(extractedText.isEmpty ? "None" : extractedText)
        Provide one improved title (max 5 words) and one improved caption (1 sentence, max 18 words).
        """

        do {
            let response = try await session.respond(to: prompt)
            return parseSuggestions(from: response.content)
        } catch {
            try await Task.sleep(for: .milliseconds(350))
            let retryResponse = try await session.respond(to: prompt)
            return parseSuggestions(from: retryResponse.content)
        }
        #else
        return AISuggestion(title: "My Artwork", caption: "A colorful creation full of imagination.")
        #endif
    }

    // MARK: - Parsing

    /// Parses an `AISuggestion` from raw language model output.
    ///
    /// Attempts JSON decoding first, then falls back to line-by-line
    /// `Title:` / `Caption:` parsing if JSON extraction fails.
    static func parseSuggestions(from content: String) -> AISuggestion {
        // Try JSON extraction first
        if let jsonRange = content.range(of: #"\{[\s\S]*\}"#, options: .regularExpression) {
            let jsonString = String(content[jsonRange])
            if let data = jsonString.data(using: .utf8),
               let decoded = try? JSONDecoder().decode(AISuggestion.self, from: data) {
                let cleanTitle = sanitize(decoded.title)
                let cleanCaption = sanitize(decoded.caption)
                if !cleanTitle.isEmpty || !cleanCaption.isEmpty {
                    return AISuggestion(
                        title: cleanTitle.isEmpty ? "My Artwork" : cleanTitle,
                        caption: cleanCaption.isEmpty ? "A colorful creation full of imagination." : cleanCaption
                    )
                }
            }
        }

        // Fallback: line-by-line parsing
        var parsedTitle = ""
        var parsedCaption = ""
        for line in content.split(separator: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.lowercased().hasPrefix("title:") {
                parsedTitle = String(trimmed.dropFirst("title:".count))
            } else if trimmed.lowercased().hasPrefix("caption:") {
                parsedCaption = String(trimmed.dropFirst("caption:".count))
            }
        }

        let cleanTitle = sanitize(parsedTitle)
        let cleanCaption = sanitize(parsedCaption)

        return AISuggestion(
            title: cleanTitle.isEmpty ? "My Artwork" : cleanTitle,
            caption: cleanCaption.isEmpty ? "A colorful creation full of imagination." : cleanCaption
        )
    }

    /// Strips leading/trailing whitespace, newlines, and surrounding quotes.
    private static func sanitize(_ text: String) -> String {
        text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
    }
}
