import 'dart:convert';

import 'package:firebase_vertexai/firebase_vertexai.dart';
import 'package:flutter/foundation.dart';

import 'gemini_usage_tracker.dart';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A title and caption pair generated by AI analysis.
class AISuggestion {
  final String title;
  final String caption;

  const AISuggestion({required this.title, required this.caption});
}

/// Result of validating whether an image is children's artwork.
class ArtworkValidationResult {
  /// Whether the image appears to be children's artwork or a creative piece.
  final bool isArtwork;

  /// Whether the image content is appropriate for a children's app.
  final bool isAppropriate;

  /// A user-facing message explaining why the image was flagged.
  final String? message;

  const ArtworkValidationResult({
    required this.isArtwork,
    required this.isAppropriate,
    this.message,
  });

  /// Image passed all checks.
  static const valid = ArtworkValidationResult(
    isArtwork: true,
    isAppropriate: true,
  );
}

/// Errors specific to AI suggestion generation.
enum AISuggestionError {
  invalidImage,
  emptyResponse,
  rateLimitExceeded;

  String get message {
    switch (this) {
      case AISuggestionError.invalidImage:
        return 'The image could not be processed.';
      case AISuggestionError.emptyResponse:
        return 'No response was received from the AI service.';
      case AISuggestionError.rateLimitExceeded:
        return 'AI usage limit reached. Please try again later.';
    }
  }
}

/// Exception wrapper for [AISuggestionError].
class AISuggestionException implements Exception {
  final AISuggestionError error;
  final String? detail;

  AISuggestionException(this.error, {this.detail});

  @override
  String toString() => detail ?? error.message;
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

/// Centralised service for generating AI-powered artwork suggestions.
///
/// Uses cloud-based analysis via Firebase Vertex AI (Gemini),
/// which can directly see the artwork image for higher quality results.
/// All Gemini calls are gated by [GeminiUsageTracker] rate limits.
class AISuggestionService {
  final GeminiUsageTracker _usageTracker;

  AISuggestionService(this._usageTracker);

  // Model names in priority order
  static const _geminiModelNames = [
    'gemini-2.5-flash',
    'gemini-2.5-flash-lite',
    'gemini-2.0-flash-001',
  ];

  // ---------------------------------------------------------------------------
  // System prompts
  // ---------------------------------------------------------------------------

  static const _generateSystemInstruction = '''
You name children's artwork with creative, fun, short titles.
You are given an image of the artwork. Focus on the SUBJECTS and SCENES
depicted (animals, people, flowers, houses, landscapes, etc.), not the colours or medium.
Rules:
- Title: 2-4 words, creative and playful, like a storybook name. Never include the child's name. Never list colours. Never say "drawing" or "painting".
- Caption: One warm sentence (max 15 words) celebrating what the child created. Be specific about subjects.
Return ONLY valid JSON: {"title":"...","caption":"..."}
''';

  static const _improveSystemInstruction = '''
You improve titles and captions for children's artwork.
You are given an image of the artwork. Focus on the SUBJECTS and SCENES depicted, not colours or medium.
Rules:
- Title: 2-4 words, creative and playful. Never include the child's name. Never list colours. Never say "drawing" or "painting".
- Caption: One warm sentence (max 15 words) celebrating what the child created.
Return ONLY valid JSON: {"title":"...","caption":"..."}
''';

  // ---------------------------------------------------------------------------
  // Image validation
  // ---------------------------------------------------------------------------

  /// Validates whether an image is children's artwork.
  ///
  /// Tries Gemini (cloud) for accurate multimodal classification.
  /// On failure, returns a safe default (valid).
  Future<ArtworkValidationResult> validateArtwork(Uint8List imageData) async {
    try {
      return await _validateWithGemini(imageData);
    } catch (e) {
      debugPrint('Artwork validation failed, allowing through: $e');
      return ArtworkValidationResult.valid;
    }
  }

  Future<ArtworkValidationResult> _validateWithGemini(
    Uint8List imageData,
  ) async {
    const prompt = '''
You are a content classifier for a children's artwork archiving app.
Analyse this image and classify it. Return ONLY valid JSON with these fields:
- "is_artwork": true if this is children's artwork, a drawing, painting, craft, collage, sketch, colouring page, or any creative piece made by a child. Photos OF artwork (e.g. a painting hanging on a wall or lying on a table) also count as true. false if this is a regular photograph, screenshot, meme, or unrelated image.
- "is_appropriate": true if the content is appropriate for a family/children's app. false if it contains nudity, violence, gore, drugs, weapons, or other adult content.
- "reason": a short (max 12 words) description of what the image shows.
Return ONLY: {"is_artwork":bool,"is_appropriate":bool,"reason":"..."}
''';

    final response = await _generateGeminiContent(
      imageData: imageData,
      prompt: prompt,
    );

    final text = response.text;
    if (text == null || text.isEmpty) {
      throw AISuggestionException(AISuggestionError.emptyResponse);
    }

    return _parseValidationResult(text);
  }

  ArtworkValidationResult _parseValidationResult(String content) {
    final jsonMatch = RegExp(r'\{[\s\S]*\}').firstMatch(content);
    if (jsonMatch == null) return ArtworkValidationResult.valid;

    try {
      final decoded =
          jsonDecode(jsonMatch.group(0)!) as Map<String, dynamic>;
      final isArtwork = decoded['is_artwork'] as bool? ?? true;
      final isAppropriate = decoded['is_appropriate'] as bool? ?? true;
      final reason = decoded['reason'] as String? ?? '';

      if (isArtwork && isAppropriate) return ArtworkValidationResult.valid;

      String message;
      if (!isAppropriate) {
        message = "This image doesn't appear appropriate for a children's app.";
      } else {
        final truncatedReason =
            reason.length > 60 ? reason.substring(0, 60) : reason;
        message = "This doesn't look like artwork. $truncatedReason";
      }

      return ArtworkValidationResult(
        isArtwork: isArtwork,
        isAppropriate: isAppropriate,
        message: message,
      );
    } catch (_) {
      return ArtworkValidationResult.valid;
    }
  }

  // ---------------------------------------------------------------------------
  // Suggestion generation
  // ---------------------------------------------------------------------------

  /// Generates a new title and caption for a child's artwork.
  ///
  /// Throws [AISuggestionException] if the rate limit is exceeded.
  /// On other failures, returns a safe default suggestion.
  Future<AISuggestion> generateSuggestions(
    Uint8List imageData, {
    String? childName,
  }) async {
    _checkUsageLimit();

    try {
      final childContext =
          childName != null && childName.isNotEmpty ? childName : 'the child';
      final prompt = '''
$_generateSystemInstruction

Child: $childContext
Name this artwork with a fun, imaginative title and a warm caption about what $childContext drew.
''';

      final response = await _generateGeminiContent(
        imageData: imageData,
        prompt: prompt,
      );

      final text = response.text;
      if (text == null || text.isEmpty) {
        throw AISuggestionException(AISuggestionError.emptyResponse);
      }

      _usageTracker.recordRequest();
      return _parseSuggestions(text);
    } catch (e) {
      if (e is AISuggestionException) rethrow;
      return const AISuggestion(
        title: 'My Artwork',
        caption: 'A colorful creation full of imagination.',
      );
    }
  }

  /// Improves an existing title and caption for a child's artwork.
  ///
  /// Throws [AISuggestionException] if the rate limit is exceeded.
  /// On other failures, returns the existing values or defaults.
  Future<AISuggestion> improveSuggestions(
    Uint8List imageData,
    String existingTitle,
    String existingCaption, {
    String? childName,
  }) async {
    _checkUsageLimit();

    try {
      final childContext =
          childName != null && childName.isNotEmpty ? childName : 'the child';
      final prompt = '''
$_improveSystemInstruction

Child: $childContext
Current title: ${existingTitle.isEmpty ? 'None' : existingTitle}
Current caption: ${existingCaption.isEmpty ? 'None' : existingCaption}
Improve the title and caption to be more creative and specific to the artwork.
''';

      final response = await _generateGeminiContent(
        imageData: imageData,
        prompt: prompt,
      );

      final text = response.text;
      if (text == null || text.isEmpty) {
        throw AISuggestionException(AISuggestionError.emptyResponse);
      }

      _usageTracker.recordRequest();
      return _parseSuggestions(text);
    } catch (e) {
      if (e is AISuggestionException) rethrow;
      return AISuggestion(
        title: existingTitle.isEmpty ? 'My Artwork' : existingTitle,
        caption: existingCaption.isEmpty
            ? 'A colorful creation full of imagination.'
            : existingCaption,
      );
    }
  }

  // ---------------------------------------------------------------------------
  // Gemini content generation
  // ---------------------------------------------------------------------------

  /// Generates multimodal content using the first available Gemini model.
  Future<GenerateContentResponse> _generateGeminiContent({
    required Uint8List imageData,
    required String prompt,
  }) async {
    Object? lastError;

    for (final modelName in _geminiModelNames) {
      try {
        // ignore: deprecated_member_use
        final model = FirebaseVertexAI.instance.generativeModel(
          model: modelName,
        );

        final imagePart = InlineDataPart('image/jpeg', imageData);
        final textPart = TextPart(prompt);

        final response = await model.generateContent([
          Content.multi([imagePart, textPart]),
        ]);

        return response;
      } catch (e) {
        lastError = e;
        debugPrint('Gemini model $modelName failed: $e');
      }
    }

    throw lastError ?? AISuggestionException(AISuggestionError.emptyResponse);
  }

  /// Generates text-only content using the first available Gemini model.
  // ignore: unused_element
  Future<GenerateContentResponse> _generateGeminiTextContent({
    required String prompt,
  }) async {
    Object? lastError;

    for (final modelName in _geminiModelNames) {
      try {
        // ignore: deprecated_member_use
        final model = FirebaseVertexAI.instance.generativeModel(
          model: modelName,
        );

        final response = await model.generateContent([
          Content.text(prompt),
        ]);

        return response;
      } catch (e) {
        lastError = e;
        debugPrint('Gemini model $modelName failed: $e');
      }
    }

    throw lastError ?? AISuggestionException(AISuggestionError.emptyResponse);
  }

  // ---------------------------------------------------------------------------
  // Usage limit check
  // ---------------------------------------------------------------------------

  void _checkUsageLimit() {
    if (!_usageTracker.canMakeRequest) {
      final exceeded = _usageTracker.exceededLimit;
      final resetDate = _usageTracker.exceededLimitResetDate;
      final detail = exceeded != null && resetDate != null
          ? exceeded.message(resetDate)
          : 'AI usage limit reached. Please try again later.';
      throw AISuggestionException(
        AISuggestionError.rateLimitExceeded,
        detail: detail,
      );
    }
  }

  // ---------------------------------------------------------------------------
  // Parsing
  // ---------------------------------------------------------------------------

  /// Parses an [AISuggestion] from raw language model output.
  AISuggestion _parseSuggestions(String content) {
    // Try JSON extraction first
    final jsonMatch = RegExp(r'\{[\s\S]*\}').firstMatch(content);
    if (jsonMatch != null) {
      try {
        final decoded =
            jsonDecode(jsonMatch.group(0)!) as Map<String, dynamic>;
        final rawTitle = decoded['title'] as String? ?? '';
        final rawCaption = decoded['caption'] as String? ?? '';
        final cleanTitle = _sanitize(rawTitle);
        final cleanCaption = _sanitize(rawCaption);

        if (cleanTitle.isNotEmpty || cleanCaption.isNotEmpty) {
          return AISuggestion(
            title: cleanTitle.isEmpty ? 'My Artwork' : cleanTitle,
            caption: cleanCaption.isEmpty
                ? 'A colorful creation full of imagination.'
                : cleanCaption,
          );
        }
      } catch (_) {
        // Fall through to line-by-line parsing
      }
    }

    // Fallback: line-by-line parsing
    String parsedTitle = '';
    String parsedCaption = '';

    for (final line in content.split('\n')) {
      final trimmed = line.trim();
      final lower = trimmed.toLowerCase();
      if (lower.startsWith('title:')) {
        parsedTitle = trimmed.substring('title:'.length);
      } else if (lower.startsWith('caption:')) {
        parsedCaption = trimmed.substring('caption:'.length);
      }
    }

    final cleanTitle = _sanitize(parsedTitle);
    final cleanCaption = _sanitize(parsedCaption);

    return AISuggestion(
      title: cleanTitle.isEmpty ? 'My Artwork' : cleanTitle,
      caption: cleanCaption.isEmpty
          ? 'A colorful creation full of imagination.'
          : cleanCaption,
    );
  }

  /// Strips leading/trailing whitespace and surrounding quotes.
  static String _sanitize(String text) {
    var result = text.trim();
    // Remove surrounding quotes
    if (result.length >= 2) {
      if ((result.startsWith('"') && result.endsWith('"')) ||
          (result.startsWith("'") && result.endsWith("'"))) {
        result = result.substring(1, result.length - 1);
      }
    }
    return result.trim();
  }
}
